export const items = {
  bins: [
    {
      id: 1,
      name: "a-bin1",
      type: "General-Waste-Bin",
      image: "/images/bins/rubbish.png",
      lid: ["red"],
      canGoIn: [
        "Household waste is anything that cannot be:",
        "re-used or recycled",
        "placed in your compost bin",
        "placed in your  yellow-lid recycling bin",
        "placed in your purple-lid glass bin",
      ],
      canNotGoIn: [
        "Hot ashes",
        "Liquids",
        "Oil, paint and solvents",
        "Syringes and needles",
        "Timber or  building materials",
        "Unwrapped vacuum dust",
        "Batteries",
        "Electronic waste (anything with a cord or battery)",
        "Clothing and  textiles",
      ],
    },
    {
      id: 2,
      name: "b-bin2",
      type: "Recycling-Bin",
      image: "/images/bins/recycling.png",
      lid: ["yellow"],
      canGoIn: [
        "Paper, cardboard, junk mail and egg cartons",
        "Aluminium foil and cans",
        "Metal lids from bottles and jars",
        "Milk, juice, soy milk and stock cartons",
        "Plastic bottles labelled 1 and 2 (lids off)",
        "All plastic food containers labelled 5",
      ],
      canNotGoIn: [
        "Glass bottles and jars (these can still be recycled in your purple glass bin)",
        "Aerosol cans",
        "Plastic lids of any kind, including trigger, spray and pump lids",
        "All plastic items labelled 1 and 2 that are not plastic bottles",
        "All plastic items labelled 3,4,6 and 7",
      ],
    },
    {
      id: 3,
      name: "c-bin3",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
      canGoIn: [
        "Glass jars (empty, no lids), Pasta sauce, jam, condiments etc",
        "Glass bottles, including broken bottles (empty, no lids), Wine bottles, Beer bottles, Spirit (alcohol) bottles, Olive oil and sauce bottles",
      ],
      canNotGoIn: [
        "Drinking glasses",
        "Broken windows and windows",
        "Broken light bulbs",
        "Vases",
        "Perfume or makeup containers",
        "Lids, corks or bottle tops",
      ],
    },
    {
      id: 4,
      name: "d-bin4",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
    },
    {
      id: 5,
      name: "e-bin5",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
    },
    {
      id: 6,
      name: "f-bin6",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
    },
    {
      id: 7,
      name: "g-bin7",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
    },
    {
      id: 8,
      name: "h-bin",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
    },
    {
      id: 9,
      name: "i-bin",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
    },
    {
      id: 10,
      name: "j-bin4",
      type: "Glass-Recycling-Bin",
      image: "/images/bins/glass.png",
      lid: ["purple"],
    },
  ],
};


